### ISSUE TITLE
 'run commands' feature is not working when a file is saved

### ISSUE THREAD

**Issue by kushal-godspeed** [godspeedsystems/gs-node-service#786] opened 2023-12-06 00:33 UTC
Right now, when we make changes in the code and save the file, the changes don't show up automatically. To see the updates, we have to restart the server. We want to add a feature so that changes are immediately visible after saving the file, without needing to restart the server. This will make things easier for developers and speed up the work

**Comment by gurjotmindgrep** [comment] 2023-12-07 08:08
@kushal-mindgrep Could you please specify the steps which you are following to start the server?

**Comment by gurjotmindgrep** [comment] 2023-12-07 11:27
The issue is fixed in [godspeed-scaffolding](https://github.com/godspeedsystems/godspeed-scaffolding). Please create a new project and check.

**Closed** 2024-02-05 17:01 UTC
Labels: feature
